MODULE CHECK_MEMORY
	USE MPI_MODULE
	 IMPLICIT NONE
CONTAINS
	SUBROUTINE CHECK_MEM(me,master,comm)
		INTEGER,INTENT(IN)::me,master,comm
		CHARACTER(LEN=20) :: FILE
		INTEGER :: SIZE=0, RESIDENT=0, SHARE=0, TEXT=0, LIB=0, DATA_LOC=0, DT=0
		INTEGER:: DATA_MAX
		INTEGER:: IERR=0

		FILE='/proc/self/statm'
		OPEN(UNIT=1,FILE=FILE,FORM='FORMATTED',STATUS='OLD',ACTION='READ',IOSTAT=IERR)
		READ(UNIT=1,FMT=*,IOSTAT=IERR) SIZE, RESIDENT, SHARE, TEXT, LIB, DATA_LOC, DT
		CLOSE(UNIT=1)

		IF (IERR < 0) THEN
			WRITE(*,*)'PROBLEM READING /PROC/SELF/STATM'
		ENDIF
		CALL MPI_REDUCE(DATA_LOC,DATA_MAX,1,MPI_INT,MPI_MAX,master,comm,IERR)
		IF (me==master) THEN
			PRINT *,'Max memory usage:', DATA_MAX*4.0/1024/1024, 'Gb'
		ENDIF
		
	END 
END
