MODULE CONST_MODULE
	REAL(8), PARAMETER ::TS=1D0
	REAL(8), PARAMETER ::TS2=1e0
	INTEGER, PARAMETER :: RealParm = KIND(TS) 
	INTEGER, PARAMETER ::RealParm2 = KIND(TS2)
  	 REAL (KIND = RealParm2),PARAMETER :: PI=3.1415926535897932384626433832795028841971693993751058209_RealParm2
	REAL (KIND = RealParm2), PARAMETER :: MU0=4.0_RealParm2*PI*1e-7_RealParm2
	REAL (KIND = RealParm), PARAMETER ::EL=0.5772156649015329D0
	INTEGER,PARAMETER::ONE=1
	INTEGER,PARAMETER::TWO=2
#ifdef FFTW_SIZE_32
	INTEGER(4),PARAMETER::FFTW_TWO=2
	INTEGER,PARAMETER:: FFTW_COMM_SIZE=4
#else
	INTEGER(8),PARAMETER::FFTW_TWO=TWO
	INTEGER,PARAMETER:: FFTW_COMM_SIZE=8
#endif


	COMPLEX(REALPARM),PARAMETER ::C_ZERO=(0e0_REALPARM,0e0_REALPARM)
	COMPLEX(REALPARM),PARAMETER ::C_ONE=(1e0_REALPARM,0e0_REALPARM)
	COMPLEX(REALPARM),PARAMETER ::C_TWO=(2e0_REALPARM,0e0_REALPARM)
	REAL(REALPARM),PARAMETER::R_ZERO=0e0_REALPARM
	LOGICAL,PARAMETER:: VERBOSE=.TRUE.
	LOGICAL,PARAMETER:: FGMRES_VERBOSE=.TRUE.
	LOGICAL,PARAMETER:: GMRES_VERBOSE=.FALSE.
	LOGICAL,PARAMETER:: FFTW_THREADS_FORCE=.TRUE.
	LOGICAL,PARAMETER:: FFTW_THREADS_DISABLE=.TRUE.
	INTEGER, PARAMETER :: EX=1
	INTEGER, PARAMETER :: EY=2
	INTEGER, PARAMETER :: EZ=3
	INTEGER, PARAMETER :: HX=4
	INTEGER, PARAMETER :: HY=5
	INTEGER, PARAMETER :: HZ=6

	INTEGER, PARAMETER :: S_EXX=1
	INTEGER, PARAMETER :: S_EXY=2
	INTEGER, PARAMETER :: S_EYX=S_EXY
	INTEGER, PARAMETER :: S_EYY=3
	INTEGER, PARAMETER :: S_EZZ=4

	INTEGER, PARAMETER :: A_EXZ=1
	INTEGER, PARAMETER :: A_EYZ=2
	INTEGER, PARAMETER :: A_EZX=A_EXZ
	INTEGER, PARAMETER :: A_EZY=A_EYZ

	INTEGER, PARAMETER :: EXX=1
	INTEGER, PARAMETER :: EXY=2
	INTEGER, PARAMETER :: EXZ=3
	INTEGER, PARAMETER :: EYX=EXY
	INTEGER, PARAMETER :: EYY=4
	INTEGER, PARAMETER :: EYZ=5
	INTEGER, PARAMETER :: EZX=EXZ
	INTEGER, PARAMETER :: EZY=EYZ
	INTEGER, PARAMETER :: EZZ=6


	INTEGER, PARAMETER :: REXX=1
	INTEGER, PARAMETER :: REXY=2
	INTEGER, PARAMETER :: REXZ=3
	INTEGER, PARAMETER :: REYX=REXY
	INTEGER, PARAMETER :: REYY=4
	INTEGER, PARAMETER :: REYZ=5
	INTEGER, PARAMETER :: REZX=6
	INTEGER, PARAMETER :: REZY=7
	INTEGER, PARAMETER :: REZZ=8


	INTEGER, PARAMETER :: RHXX=1
	INTEGER, PARAMETER :: RHXY=2
	INTEGER, PARAMETER :: RHXZ=3
	INTEGER, PARAMETER :: RHYX=4
	INTEGER, PARAMETER :: RHYY=RHXX  !dirty hack !!!!
	INTEGER, PARAMETER :: RHYZ=5
	INTEGER, PARAMETER :: RHZX=6
	INTEGER, PARAMETER :: RHZY=7

END MODULE 
