!Copyright (c) 2016 Mikhail Kruglyakov 
!This file is part of GIEM2G.
!
!GIEM2G is free software: you can redistribute it and/or modify
!it under the terms of the GNU General Public License as published by
!the Free Software Foundation, either version 2 of the License.
!
!GIEM2G is distributed in the hope that it will be useful,
!but WITHOUT ANY WARRANTY; without even the implied warranty of
!MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
!GNU General Public License for more details.
!
!You should have received a copy of the GNU General Public License
!along with GIEM2G.  If not, see <http://www.gnu.org/licenses/>.
!
!
!

MODULE CONST_MODULE
	USE, INTRINSIC :: iso_c_binding
#ifndef NOT_USE_OMP_LIB
	USE, INTRINSIC :: OMP_LIB
#endif
	INTEGER, PARAMETER ::REALPARM = SELECTED_REAL_KIND(15)
	INTEGER, PARAMETER ::REALPARM2 = SELECTED_REAL_KIND(15)
	INTEGER, PARAMETER  ::DOUBLEPARM=SELECTED_REAL_KIND(15)

        INTEGER, PARAMETER :: SHORT_INT=SELECTED_INT_KIND(7)	
        INTEGER, PARAMETER :: LONG_INT=SELECTED_INT_KIND(15)	

	REAL (KIND = REALPARM2),PARAMETER :: PI=3.1415926535897932384626433832795028841971693993751058209_REALPARM2
	REAL (KIND = REALPARM2), PARAMETER :: MU0=4.0_REALPARM2*PI*1E-7_REALPARM2
	REAL(REALPARM),PARAMETER::EPS0=1.0_REALPARM/(MU0*299792458*299792458);
	
	REAL(REALPARM),PARAMETER::AIR_CONDUCTIVITY=1e-12_REALPARM
	INTEGER,PARAMETER::ZERO=0
	INTEGER,PARAMETER::ONE=1
	INTEGER,PARAMETER::TWO=2
#ifdef FFTW_SIZE_32
	INTEGER(4),PARAMETER::FFTW_TWO=2
	INTEGER,PARAMETER:: FFTW_COMM_SIZE=4
#else
	INTEGER(C_INTPTR_T),PARAMETER::FFTW_TWO=TWO
	INTEGER,PARAMETER:: FFTW_COMM_SIZE=KIND(TWO)
#endif


!-----------------------------------------------------------------------------!
	COMPLEX(REALPARM),PARAMETER ::	C_ZERO=(0e0_REALPARM,0e0_REALPARM)
	COMPLEX(REALPARM),PARAMETER ::	C_ONE=(1e0_REALPARM,0e0_REALPARM)
	COMPLEX(REALPARM),PARAMETER ::	C_IONE=(0e0_REALPARM,1e0_REALPARM)
	COMPLEX(REALPARM),PARAMETER ::	C_TWO=(2e0_REALPARM,0e0_REALPARM)
	REAL(REALPARM)   ,PARAMETER ::	R_ZERO=0e0_REALPARM
	REAL(REALPARM)   ,PARAMETER ::	R_ONE=1e0_REALPARM

!-----------------------------------------------------------------------------!
INTERFACE
#ifdef NOT_USE_OMP_LIB
        FUNCTION OMP_GET_NUM_THREADS() RESULT (NT)
                   INTEGER:: NT
        ENDFUNCTION
        FUNCTION OMP_GET_MAX_THREADS() RESULT (NT)
                   INTEGER:: NT
        ENDFUNCTION
        
        FUNCTION OMP_GET_THREAD_NUM() RESULT (NT)
                   INTEGER:: NT
        ENDFUNCTION
#endif
ENDINTERFACE
!-----------------------------------------------------------------------------!
#ifndef ExtrEMe
	INTEGER, PARAMETER :: EX=1
	INTEGER, PARAMETER :: EY=2
	INTEGER, PARAMETER :: EZ=3
	INTEGER, PARAMETER :: HX=4
	INTEGER, PARAMETER :: HY=5
	INTEGER, PARAMETER :: HZ=6
#else
	INTEGER, PARAMETER :: EX=2
	INTEGER, PARAMETER :: EY=1
	INTEGER, PARAMETER :: EZ=3
	INTEGER, PARAMETER :: HX=5
	INTEGER, PARAMETER :: HY=4
	INTEGER, PARAMETER :: HZ=6
#endif
!-----------------------------------------------------------------------------!
	INTEGER, PARAMETER :: S_EXX=1
	INTEGER, PARAMETER :: S_EXY=2
	INTEGER, PARAMETER :: S_EYX=S_EXY
	INTEGER, PARAMETER :: S_EYY=3
	INTEGER, PARAMETER :: S_EZZ=4

	INTEGER, PARAMETER :: A_EXZ=1
	INTEGER, PARAMETER :: A_EYZ=2
	INTEGER, PARAMETER :: A_EZX=A_EXZ
	INTEGER, PARAMETER :: A_EZY=A_EYZ

!-----------------------------------------------------------------------------!
	INTEGER, PARAMETER :: EXX=1
	INTEGER, PARAMETER :: EXY=2
	INTEGER, PARAMETER :: EXZ=3
	INTEGER, PARAMETER :: EYX=EXY
	INTEGER, PARAMETER :: EYY=4
	INTEGER, PARAMETER :: EYZ=5
	INTEGER, PARAMETER :: EZX=EXZ
	INTEGER, PARAMETER :: EZY=EYZ
	INTEGER, PARAMETER :: EZZ=6

!-----------------------------------------------------------------------------!

	INTEGER, PARAMETER :: REXX=1
	INTEGER, PARAMETER :: REXY=2
	INTEGER, PARAMETER :: REXZ=3
	INTEGER, PARAMETER :: REYX=REXY
	INTEGER, PARAMETER :: REYY=4
	INTEGER, PARAMETER :: REYZ=5
	INTEGER, PARAMETER :: REZX=6
	INTEGER, PARAMETER :: REZY=7
	INTEGER, PARAMETER :: REZZ=8


	INTEGER, PARAMETER :: RHXX=1
	INTEGER, PARAMETER :: RHXY=2
	INTEGER, PARAMETER :: RHXZ=3
	INTEGER, PARAMETER :: RHYX=4
	INTEGER, PARAMETER :: RHYY=RHXX  !dirty hack !!!!
	INTEGER, PARAMETER :: RHYZ=5
	INTEGER, PARAMETER :: RHZX=6
	INTEGER, PARAMETER :: RHZY=7
!-----------------------------------------------------------------------------!
	LOGICAL,PARAMETER:: VERBOSE=.TRUE.
	LOGICAL,PARAMETER:: FGMRES_VERBOSE=.TRUE.
	LOGICAL,PARAMETER:: GMRES_VERBOSE=.FALSE.

	LOGICAL,PARAMETER:: FFTW_THREADS_FORCE=.TRUE.

	LOGICAL,PARAMETER:: FFTW_THREADS_DISABLE=.FALSE.
END MODULE 
