MODULE TIMER_MODULE
	USE CONST_MODULE 	
	REAL(DOUBLEPARM)::StartTime
	INTEGER,PARAMETER::KIND8=SELECTED_INT_KIND(15)
	INTEGER(KIND8)::StartCount
	INTEGER(KIND8)::CountRate
	CONTAINS
#ifndef MPI_TIMER
	SUBROUTINE InitTimer
		REAL(DOUBLEPARM)::t1,t2
		CALL SYSTEM_CLOCK(StartCount, CountRate)
		t1=StartCount
		t2=CountRate
		StartTime=t1/t2
	ENDSUBROUTINE
#else
	SUBROUTINE InitTimer
	ENDSUBROUTINE
#endif
#ifndef MPI_TIMER
	FUNCTION GetTime() RESULT(t)
		INTEGER(KIND8)::Ticks
		REAL(DOUBLEPARM)::t1
		CALL SYSTEM_CLOCK(Ticks)
		t1=(Ticks-StartCount)
		t=t1/CountRate
	ENDFUNCTION
#else
	FUNCTION GetTime() RESULT(t)
		USE MPI_MODULE
		t=MPI_Wtime()
	ENDFUNCTION
#endif
END MODULE 
